# Generated by Django 6.1.1 on 2026-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='condicion_fiscal',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='direccion',
            field=models.CharField(blank=True, default='generic', null=True),
        ),
    ]
