# Generated by Django 6.1.1 on 2026-09-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_condicion_fiscal_client_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='punto_venta',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
