# Generated by Django 6.1.1 on 2026-09-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT/CUIL')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Código interno (SKU)', max_length=50, null=True, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta base sin IVA', max_digits=12)),
                ('alicuota', models.DecimalField(choices=[(0.0, '0% (Exento)'), (10.5, '10.5%'), (21.0, '21.0%'), (27.0, '27.0%')], decimal_places=2, default=21.0, max_digits=5)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('M', 'Metro Lineal'), ('M2', 'Metro Cuadrado'), ('M3', 'Metro Cúbico'), ('L', 'Litro'), ('PACK', 'Pack / Bulto'), ('BOL', 'Bolsa'), ('PAL', 'Pallet')], default='UN', max_length=5)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_critico', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
                ('proveedores', models.ManyToManyField(blank=True, related_name='productos', to='productos.proveedor')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.subcategoria')),
            ],
        ),
    ]
