# Generated by Django 6.1.1 on 2026-09-19 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_fiscal', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', max_length=2)),
                ('cuit', models.CharField(max_length=12)),
                ('direcciones', models.TextField(blank=True, help_text='Soporta múltiples direcciones de obra o entrega', null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, help_text='Capacidad de carga en KG', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva_total_discriminado', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='sales.cliente')),
                ('presupuestante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, help_text='Precio al momento de presupuestar', max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.producto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_total_discriminado', models.JSONField(blank=True, default=dict)),
                ('tipo_factura', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('X', 'Remito / Comprobante Interno')], max_length=1)),
                ('receptor', models.CharField(help_text='Razón social o Nombre de quien factura', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('punto_venta', models.CharField(help_text='Ej: 0004', max_length=10)),
                ('cae', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, null=True)),
                ('totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.cliente')),
                ('presupuesto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='venta_asociada', to='sales.presupuesto')),
                ('vendedor', models.ForeignKey(help_text='Usuario que concretó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente de Armado'), ('A', 'Armado / Listo'), ('C', 'En Camino'), ('E', 'Entregado'), ('X', 'Cancelado / Reprogramado')], default='P', max_length=1)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.chofer')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.vehiculo')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='sales.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta')),
            ],
        ),
    ]
