# Generated by Django 6.1.1 on 2026-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad_kg',
        ),
        migrations.AddField(
            model_name='chofer',
            name='apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='dni',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga_kg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Capacidad máxima en kg', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
