# Generated by Django 6.1.1 on 2026-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_vehiculo_capacidad_kg_chofer_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('SALDADA', 'Saldada'), ('IMPAGA', 'Impaga / Pendiente')], default='SALDADA', max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CHEQUE', 'Cheque'), ('CTA_CTE', 'Cuenta Corriente')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='punto_venta',
            field=models.CharField(default='0001', help_text='Ej: 0004', max_length=10),
        ),
    ]
